target:
  class_path: vonmises.distributions.VonMisesFisherMixtureDensity
  init_args:
    κ: [10, 10, 10]
    μ: [[0, 1, 0], [0, -1, 0], [0, 0, 1]]
    weights: [1, 1, 1]

flow:
  class_path: vonmises.flows.RecursiveFlowS2
  init_args:
    z_transformer:
      class_path: vonmises.transforms.BSplineTransform
      init_args:
        n_segments: 12
    xy_transformer:
      class_path: vonmises.transforms.MobiusMixtureTransform
      init_args:
        n_mixture: 12
        weighted: true
    n_layers: 1
    net_hidden_shape: []

steps: 4000
batch_size: 4000
