target:
  class_path: VonMisesFisherDensity
  init_args:
    κ: 10
    μ: [1, 0]

flow:
  class_path: CircularFlow
  init_args:
    transform:
      class_path: MobiusModule
      init_args:
        n_mixture: 4

steps: 1000
batch_size: 1000
