target:
  class_path: VonMisesFisherDensity
  init_args:
    κ: 10
    μ: [1, 1, 1, 0]

flow:
  class_path: RecursiveFlowSD
  init_args:
    interval_transforms:
      - class_path: SigmoidModule
        init_args:
          n_mixture: 8
      - class_path: SigmoidModule
        init_args:
          n_mixture: 8
          net_hidden_shape: [100]
          net_activation: ReLU
    circular_transform:
      class_path: CircularSigmoidModule
      init_args:
        n_mixture: 8
        net_hidden_shape: [100]
        net_activation: ReLU
    ordering: [1, 2, 3, 4]

steps: 2000
batch_size: 2000
